#ifndef EXIT_STATUSES_H
# define EXIT_STATUSES_H

enum e_retvals
{
	MS_SUCCESS = 0,
	MS_FAILURE = 1,
	MS_BUILTIN_MISUSE = 2,
	MS_PERM_DENIED = 126,
	MS_CMD_NOT_FOUND = 127,
	MS_SIGNAL_EXIT = 128,
	MS_UNEXPECTED = 255,
};
#endif // !EXIT_STATUSES_H
